>RedJungleFowl
------------------------------------------------------------
--------------------------------SARDYNGHRNAVLARFWNPSGSVCDGSY
AFLHKAI-----------------------------------YHCFFKHFFTTLRYTS--
------------------------------------------------------------
----------------------------------------WKSSNKHLIYQAPGLPKCNQ
NGASFSSLFFKSAVIQTSRGVFQLTYGYMSCV---------WGQGLWISLWSACMR----
---------------LGLFSKNNQIKAYLVPLSHPEKQKVSILQISEMSCS---------
----------WNVTCHQVWANATSGEGEALGXXFQRHRXXKSICSASA------------
-------------------------------------CXX--------------------
----
>AustralianZebraFinch
------------------------------------------------------------
-----------------------------------------GGGRLREWGRAGQEQPGGV
HLGTRMMPELQG------------------------------LQSWHGVINYGTTTGGST
------------------------------------------------------------
--------------------------GQGRGRGRGSDGGKWSLRPNWRTRQLAAFKQLHR
PVTELLSLAVGPAADGLRGG----------------------GAGSAERG-VQGLRR---
-------------QSLGLPLRRARLRGLQGFLPPDDPHEAGVREVEELQDSEEEQKQVPV
LPLPEMPLAGHVTQCNPLWAHAGREEEAGGRADSERDQLPEPTGGPESFLQAHLQRLPEE
FQHDQK---------------EGKRYPDRQGQQHPTFCDPHGHPVAGGEGAGVX------
----
>WhireRumpedMunia
------------------------------------------------------------
----------------------------------------------------GGKANNNP
PFVIHDMDT---------------------------------LCMAEKTLVAKLVANGIQ
------------------------------------------------------------
--------------------------------NKEAEVRIFHCCQCTSVETVTELTEFAK
SIPGFSSLDLNDQVTLLKYGVYEAIFAMLASVMNKGGMLVAYGNGFITREFLKSLRKPFC
DIMEPKFDFAMKFNALDLDDSDISLFVAAIICCGDRPGLVNVGHIEKMQES--------I
VHVLKLHLQNNHPDDTFLFPKLLQKMADLRQLVTEHAQLVQIIKKTES--DAHLHPLLQE
IYRGYVLRTFSIFFHKYLKTEKFRMGSKTTXYSYGLFXQPXSRKNLKLGXLGVLXFFWVW
DLLS
>Human_PPARG
MVDTEMPFWPTNFGISSVDLSVMEDHSHSFDIKPFTTVDFSSISTPHYEDIPFTRTDPVV
ADYKYDLKLQEYQSAIKVEPASPPYYSEKTQLYNKPHEEPSNSLMAIECRVCGDKASG-F
HYGVHACEGCKGFFRRTIRLKLIYDRCDLNCRIHKKSRNKCQYCRFQKCLAVGMSHNAIR
FGRMPQAEKEKLLAEISSDIDQLNPESADLRALAKHLYDSYIKSFPLTKAKARAILTGKT
TDKSPFVIYDMNSLMMGEDKIKFKHITPLQEQSKEVAIRIFQGCQFRSVEAVQEITEYAK
SIPGFVNLDLNDQVTLLKYGVHEIIYTMLASLMNKDGVLISEGQGFMTREFLKSLRKPFG
DFMEPKFEFAVKFNALELDDSDLAIFIAVIILSGDRPGLLNVKPIEDIQDN--------L
LQALELQLKLNHPESSQLFAKLLQKMTDLRQIVTEHVQLLQVIKKTET--DMSLHPLLQE
IYKDLY------------------------------------------------------
----
>GreylagGoose
------------------------------------------------------------
------------------------------------HEESTNSLMAIECRVCGDKASG-F
HYGVHACEGCKGFFRRTIRLKLIYDRCDLNCRIDKKSRNKCQYCRFQKCLAVGMRHNAIR
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------FGRX---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
